"""Write docs/reference/ from the code: the CLI, the configuration, the run states and the bot.

Run `uv run tools/gen_docs.py` after a change to a command, a flag, a config key, a state or a
bot command. `--check` exits 1 with a diff summary when a committed page differs.
"""

from __future__ import annotations

import argparse
import difflib
import inspect
import os
import sys
from collections.abc import Iterable
from dataclasses import MISSING, Field, asdict, fields, is_dataclass
from pathlib import Path
from unittest import mock

from edarunner import board, cli, config, model, watch
from edarunner.notify import alert_buttons
from edarunner.notify.telegram import bot as tg
from edarunner.notify.telegram import commands as tgc
from edarunner.notify.telegram import format as tgfmt

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "reference"
HEAD = "<!-- Generated by tools/gen_docs.py from the code. Do not edit; run `uv run tools/gen_docs.py`. -->\n\n"
Part = type | tuple[type, list[str]]
TG = ("In `edr.toml` the table takes `token_file`, `chat_id`, `user_id` and `topic_id` of the site's `[telegram]` table and "
      "replaces them for this project only. A key it leaves out keeps the site's value. Without a `[telegram]` "
      "table in `site.toml`, the table here needs `chat_id`. The custom commands stay in `site.toml`.")
# The sections of configuration.md: the heading, the dataclasses (or some of their fields) it lists, and the
# prose above the table; "" takes the docstring of the first dataclass.
CONFIG: list[tuple[str, list[Part], str]] = [
    ("## edr.toml", [(model.Project, ["project", "site", "state_dir", "data", "run_prefix", "telegram_poll", "env"])], ""),
    ("### [source]", [model.Source], ""),
    ("### [sync]", [model.Sync], ""),
    ("### [safety]", [model.Safety], ""),
    ("### [limits]", [model.Limits], ""),
    ("### [placement]", [model.Placement], ""),
    ("### [telegram]", [], TG),
    ("### [marks]", [], "The table is optional. It takes the keys of the site's `[marks]` table and replaces them for this "
                       "project only. A key it leaves out keeps the site's value."),
    ("### [stages.<name>]", [model.Stage], ""),
    ("#### needs", [model.Needs], ""),
    ("#### budget", [model.Budget], ""),
    ("#### retry", [model.Retry], ""),
    ("### [metrics.<name>]", [model.Metric], ""),
    ("## site.toml", [(model.Site, ["scratch", "env", "ssh_options", "ssh_timeout_s", "tool_procs", "nfs_export", "scheduler_backend"])], ""),
    ("### [hosts.<name>]", [model.Host], ""),
    ("### [marks]", [model.Marks], ""),
    ("### [tools.<name>]", [model.Tool], ""),
    ("### [telegram]", [model.Telegram], ""),
    ("### [telegram.commands.<name>]", [], "One table per custom bot command; `bot.md` lists the keys."),
    ("## tasks.toml", [model.Task, (model.Project, ["task_resolver"])], ""),
    ("## jobs/<batch>.toml", [model.Batch], ""),
    ("### [[job]]", [model.Job], ""),
]


# markdown

def cell(text: object) -> str:
    """One table cell: no pipe and no line break."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def table(head: list[str], rows: Iterable[Iterable[object]]) -> str:
    """A pipe table."""
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    lines += ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows]
    return "\n".join(lines) + "\n"


def code(text: object) -> str:
    return f"`{text}`" if text else ""


def doc(obj: object) -> str:
    """The docstring of a class, function or module; none for the signature a dataclass writes itself."""
    text = inspect.cleandoc(obj.__doc__ or "")
    return "" if text.startswith(getattr(obj, "__name__", "\0") + "(") else text


# the CLI

def commands() -> dict[str, argparse.ArgumentParser]:
    """Every command's parser, in the order of the definitions."""
    p = cli._parser()
    sub = next(a for a in p._actions if isinstance(a, argparse._SubParsersAction))
    return {name: s for name, s in sub.choices.items() if name in cli.EXITS}  # an alias without help stays out


def _usage(p: argparse.ArgumentParser) -> str:
    with mock.patch.dict(os.environ, {"COLUMNS": "200"}):  # argparse wraps the usage at the terminal width
        return p.format_usage().removeprefix("usage: ").replace(" [-h]", "").strip()


def _flag(a: argparse.Action) -> str:
    if not a.option_strings:
        return code(f"[{a.dest}]" if a.nargs == "?" else a.dest)
    name = ", ".join(a.option_strings)
    if a.nargs == 0:
        return code(name)
    meta = a.metavar or a.dest.upper()
    return code(f"{name} {meta} ..." if a.nargs == "+" else f"{name} {meta}")


def _flags(p: argparse.ArgumentParser) -> str:
    actions = [a for a in p._actions if not isinstance(a, (argparse._HelpAction, argparse._SubParsersAction))]
    rows = [[_flag(a), (a.help or "") + (", required" if a.required and a.option_strings else "")]
            for a in sorted(actions, key=lambda a: bool(a.option_strings))]  # positionals first, as in --help
    return table(["Flag", "Meaning"], rows) if rows else ""


def cli_page() -> str:
    p = cli._parser()
    out = [HEAD, "# The edr command\n\n", f"```\n{_usage(p)}\n```\n\n", p.description + "\n\n", _flags(p), "\n",
           p.epilog + "\n\n", "## Exit codes\n\n",
           table(["Code", "Meaning"], [[int(c), t] for c, t in cli.EXIT.items()]),
           "\nA command below says where it refines a code.\n\n"]
    for name, s in commands().items():
        out += [f"## {name}\n\n", f"```\n{_usage(s)}\n```\n\n", s.description + "\n\n", _flags(s)]
        if cli.EXITS[name]:
            out += ["\n", table(["Exit", "Meaning"], [[int(c), t] for c, t in sorted(cli.EXITS[name].items())])]
        out.append("\n")
    return "".join(out).rstrip() + "\n"


# the configuration

def _default(f: Field) -> str:
    if "default" in f.metadata:
        return str(f.metadata["default"])
    if f.default is not MISSING:
        return code(_toml(f.default))
    if f.default_factory is not MISSING:
        return code(_toml(f.default_factory()))
    return "required"


def _toml(value: object) -> str:
    if value is None:
        return "none"
    if is_dataclass(value) and not isinstance(value, type):
        return _toml({k: v for k, v in asdict(value).items() if v is not None})
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (str, Path)):
        return f'"{value}"'
    if isinstance(value, list):
        return "[" + ", ".join(_toml(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{k} = {_toml(v)}" for k, v in value.items()) + " }" if value else "{}"
    return str(value)


def _rows(part: Part) -> list[list[str]]:
    cls, names = part if isinstance(part, tuple) else (part, None)
    out = []
    for f in fields(cls):
        if "doc" in f.metadata and (names is None or f.name in names):
            out.append([code(f.metadata.get("key", f.name)), f.metadata["doc"], _default(f)])
    return out


def fields_table(*parts: Part) -> str:
    """The Key, Meaning, Default table of the documented fields of the dataclasses."""
    rows = [r for p in parts for r in _rows(p)]
    return table(["Key", "Meaning", "Default"], rows) if rows else ""


def config_page() -> str:
    out = [HEAD, "# Configuration\n\n", doc(config) + "\n\n"]
    for heading, parts, prose in CONFIG:
        out.append(f"{heading}\n\n")
        first = parts[0] if parts else None
        prose = prose or (doc(first[0] if isinstance(first, tuple) else first) if first else "")
        if prose:
            out.append(prose + "\n\n")
        rows = fields_table(*parts)
        if rows:
            out.append(rows + "\n")
    out += ["## Placeholders\n\n", "\n\n".join(doc(config.render).split("\n\n")[1:]) + "\n\n",
            table(["Placeholder", "Value", "Where"], [[code("{" + k + "}"), v, w] for k, (v, w) in config.PLACEHOLDERS.items()])]
    return "".join(out).rstrip() + "\n"


# the run states

def states_page() -> str:
    row = {"label": "<label>", "batch": "<batch>", "src": "<src>", "stage": "<stage>"}
    hb = {"stage": "<stage>", "step_name": "<step>"}
    rows = [[code(s), tgfmt.MARK.get(s, ""), st.test, "yes" if st.alert else "", st.action,
             code(board.triage_cmd(row, s, hb))] for s, st in watch.STATES.items()]
    return "".join([HEAD, "# Run states\n\n", doc(watch.State) + "\n\n",
                    table(["State", "Mark", "Test", "Alert", "Action", "Proposed command"], rows)])


# the bot

def bot_page() -> str:
    out = [HEAD, "# The Telegram bot\n\n", doc(tg) + "\n\n", "## Built-in commands\n\n",
           "A handle is `label@batch`, a run id prefix, or `#n` from the last board.\n\n"]
    groups: dict[str, list[tgc.Builtin]] = {}
    for b in tgc.BUILTINS.values():
        groups.setdefault(b.group, []).append(b)
    for group, cmds in groups.items():
        out += [f"### {group}\n\n", table(["Command", "Effect"], [[code(f"/{b.name} {b.args}".rstrip()), b.help] for b in cmds]), "\n"]
    out += ["Old names that still answer: " + ", ".join(f"{code('/' + old)} for {code('/' + new)}" for old, new in tgc.ALIASES.items())
            + ".\n\n"]
    out += ["## Alert buttons\n\n", table(["Button", "callback_data"], [[label, code(data)] for label, data in alert_buttons("<handle>")]),
            "\n## Custom commands\n\n", doc(model.BotCommand) + "\n\n", fields_table(model.BotCommand)]
    return "".join(out).rstrip() + "\n"


# the index

def index_page() -> str:
    rows = [["[cli.md](cli.md)", "every command with its flags, description and exit codes", "the argparse definitions in `src/edarunner/cli.py`"],
            ["[configuration.md](configuration.md)", "every key of the four TOML files, and the placeholders",
             "the dataclasses in `src/edarunner/model.py`, `PLACEHOLDERS` in `src/edarunner/config.py`"],
            ["[states.md](states.md)", "every run state: test, action, mark, proposed command",
             "`STATES` in `src/edarunner/watch.py`, `MARK` in `src/edarunner/notify/telegram/format.py`, `triage_cmd` in `src/edarunner/board.py`"],
            ["[bot.md](bot.md)", "the built-in bot commands, the alert buttons, the custom command keys",
             "`BUILTINS` in `src/edarunner/notify/telegram/commands.py`, `BotCommand` in `src/edarunner/model.py`"]]
    return "".join([HEAD, "# Reference\n\n",
                    "`tools/gen_docs.py` writes these pages from the code. Do not edit them. ",
                    "`uv run tools/gen_docs.py` regenerates them; `--check` refuses a stale page, and CI runs the check.\n\n",
                    table(["Page", "What it covers", "Source"], rows)])


# entry points

def pages() -> dict[str, str]:
    """Every page by file name."""
    return {"README.md": index_page(), "cli.md": cli_page(), "configuration.md": config_page(),
            "states.md": states_page(), "bot.md": bot_page()}


def write(out: Path) -> None:
    """Write every page under `out`."""
    out.mkdir(parents=True, exist_ok=True)
    for name, text in pages().items():
        (out / name).write_text(text)


def check(out: Path) -> int:
    """1 with a diff summary when a page under `out` differs from what `write` would put there."""
    stale = []
    for name, text in pages().items():
        path = out / name
        old = path.read_text() if path.is_file() else ""
        if old == text:
            continue
        stale.append(name)
        diff = difflib.unified_diff(old.splitlines(), text.splitlines(), f"{name} (committed)", f"{name} (generated)", lineterm="", n=0)
        print("\n".join(list(diff)[:40]))
    if stale:
        print(f"stale: {', '.join(stale)}; run: uv run tools/gen_docs.py", file=sys.stderr)
    return 1 if stale else 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true", help="compare with the committed pages; exit 1 on a difference")
    a = p.parse_args(argv)
    if a.check:
        return check(OUT)
    write(OUT)
    print(f"wrote {len(pages())} pages to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
